### ISSUE TITLE
"unavailable"

### ISSUE THREAD

**Issue by SteveRMann** [gagebenne/home-assistant-dexcom#3]
I have been enjoying the simplicity of this custom component to get my Dexcom readings for a few weeks. It's been reliable.
However, for the past day, all I get is "unavailable".

I now that my data is sharing because I can still get it through a RESTful call to my Heroku app.
What else can cause the custom component to return "unavailable"?

**Comment by gagebenne** [comment]
Hm, it could be that the session expired, and the integration failed to get another. This repository is slightly out of date compared to the pull request, and some changes are underway with better session handling.

Could you send any log information? Also, this unavailability is from both the value and state sensor, right?

**Comment by SteveRMann** [comment]
Thanks. Yes, both are "unavailable"

Here's the lines from the log file:

`2020-06-25 00:41:30 WARNING (MainThread) [homeassistant.components.sensor] Platform wunderground not ready yet. Retrying in 30 seconds.
2020-06-25 00:41:30 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry SteveRMann for dexcom
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 308, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd0b57e6f50>: Failed to establish a new connection: [Errno -3] Try again

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='share2.dexcom.com', port=443): Max retries exceeded with url: /ShareWebServices/Services/General/LoginPublisherAccountByName (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0b57e6f50>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pydexcom/__init__.py", line 60, in _request
    json=json,
  File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='share2.dexcom.com', port=443): Max retries exceeded with url: /ShareWebServices/Services/General/LoginPublisherAccountByName (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd0b57e6f50>: Failed to establish a new connection: [Errno -3] Try again'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/config/custom_components/dexcom/__init__.py", line 60, in async_setup_entry
    Dexcom, entry.data[CONF_USERNAME], entry.data[CONF_PASSWORD]
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pydexcom/__init__.py", line 40, in __init__
    self.create_session()
  File "/usr/local/lib/python3.7/site-packages/pydexcom/__init__.py", line 103, in create_session
    "post", DEXCOM_LOGIN_ENDPOINT, headers=headers, json=json
  File "/usr/local/lib/python3.7/site-packages/pydexcom/__init__.py", line 86, in _request
    _LOGGER.error(f"{r.status_code}")
UnboundLocalError: local variable 'r' referenced before assignment
2020-06-25 00:41:30 ERROR (MainThread) [metno] https://aa015h6buqvih86i1.api.met.no/weatherapi/locationforecast/1.9/ returned Cannot connect to host aa015h6buqvih86i1.api.met.no:443 ssl:None [Try again]
2020-06-25 00:41:30 ERROR (MainThread) [homeassistant.components.met.weather] Retrying in 15 minutes
2020-06-25 00:41:35 WARNING (MainThread) [homeassistant.config_entries] Config entry for upnp not ready yet. Retrying in 5 seconds.





`

**Comment by gagebenne** [comment]
This is helpful! One last question, could you let me know what country you are based?

**Comment by SteveRMann** [comment]
U.S.
Are you seeing anything in my log data?  Am I the only user with this problem?

**Comment by gagebenne** [comment]
Nothing from anyone else at this point in time, and currently everything is passing on my side. If you uninstall and reinstall the integration, does the error still occur? It looks like the integration was reloaded at some point, and failed then.

```bash
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 217, in async_setup
    hass, self
  File "/config/custom_components/dexcom/__init__.py", line 60, in async_setup_entry
    Dexcom, entry.data[CONF_USERNAME], entry.data[CONF_PASSWORD]
```

**Comment by SteveRMann** [comment]
I had a reason to reboot the server that Home Assistant is installed on, and now the component is working.
This is strange because rebooting the server is usually one of my first steps in running down a problem with Home Assistant. (First, restart HA. And if that doesn't solve the problem, reboot the server.) But I may have skipped that step because everything else was running just fine.

I have another question, but I'll start a new thread to keep our git comments clean.
